connections {
    vpp-nodeb {
        version = 2

        local_addrs = 192.168.50.2
        remote_addrs = 192.168.50.1

        # Matches VPP: ike-crypto-alg aes-cbc 256 ike-integ-alg hmac-sha2-256-128 ike-dh modp-2048
        proposals = aes256-sha256-modp2048

        local {
            auth = psk
            id = 192.168.50.2
        }

        remote {
            auth = psk
            id = 192.168.50.1
        }

        children {
            vpp-child {
                local_ts = 10.20.0.0/24
                remote_ts = 10.10.0.0/24

                # Fix: Use standard strongSwan format for ESP proposal (AES-256-CBC with SHA256-128 ICV)
                esp_proposals = aes256-sha256

                start_action = start
                #dpd_action = restart
                dpd_action = clear
        	life_time = 90s
        	rekey_time = 45s
            }
        }
    }
}

secrets {
    ike-psk {
        id-1 = 192.168.50.1
        id-2 = 192.168.50.2
        secret = secret123
    }
}
